name: Sherpa CI

on: 
  push:
    paths:
    - '**.md'
    - '**.yml'
    - '**.js'
    - '**.mdx'
  workflow_dispatch:
jobs:
  trigger:
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - name: Trigger Workflow in Another Repository
        env:
          GH_TOKEN: ${{ secrets.SHERPA_TOKEN }}
          repo_owner: "the-unnamed-nug" 
          repo_name: "sherpa"  
          event_type: "build_site"
        run: |
          curl -L \
            -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer $GH_TOKEN" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/$repo_owner/$repo_name/dispatches \
            -d "{\"event_type\": \"$event_type\"}"

